### ISSUE TITLE
Unable to class load the plugin net.epoxide.musica.asm.MusicaLoadingPlugin

### ISSUE THREAD

**Issue by TheSlimeMan** [Epoxide-MC/Musica#3]
Was trying to figure out why I had issues with this. At first I didn't have the mod, so I downloaded it. Running it again produced the same results. could someone help me so I can create my modpack?
------------HERE IS THE LOG---------------
http://pastebin.com/sZgbG66a

EDIT: IT HAS BEEN FIXED
EDIT EDIT: sry I thought :(

**Comment by TheSlimeMan** [comment]
Nevermind. i'm such a doofus....
case closed

**Comment by darkhax** [comment]
Hello there, I am curious as to what caused the issue. Can you elaborate on how you solved the issue?

**Comment by TheSlimeMan** [comment]
I thought that I was misssing CoFH core, and I was, but that was not the problem

**Comment by darkhax** [comment]
So, you are still having the crash?

**Comment by TheSlimeMan** [comment]
yup

**Comment by darkhax** [comment]
Post your new crash log, so I can read that one. If you added COFH core, things will have changes.

**Comment by TheSlimeMan** [comment]
http://pastebin.com/sMbfyf5z

**Comment by darkhax** [comment]
One of the mods you have installed is for minecraft 1.8 rather than 1.7.

**Comment by darkhax** [comment]
If you want further help, you will need to post the entire crash log, as it is being cut off. If there is a pastebin length restriction, use gist instead.

**Comment by TheSlimeMan** [comment]
oh ok, will do next time

**Comment by TheSlimeMan** [comment]
ummmm... i'm wondering which mod :l but I can't find the full report. Should it be under (user)/AppData/Roaming/.minecraft/crash-reports?
-----------------------

**Comment by TheSlimeMan** [comment]
ummm help?

**Comment by darkhax** [comment]
Yes you are in the right location. You're missing the -- System Details -- bit, in your post.

**Comment by TheSlimeMan** [comment]
huh doesn't show up in the launcher, and I have no documented crash log in the crash-reports folder O_o

**Comment by TheSlimeMan** [comment]
it should look something like this, right?

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.7.0_79, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 50476976 bytes (48 MB) / 275914752 bytes (263 MB) up to 2134114304 bytes (2035 MB)
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.130.1395 Minecraft Forge 10.13.3.1395 32 mods loaded, 32 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	FML{7.10.130.1395} [Forge Mod Loader] (forge-1.7.10-10.13.3.1395-1710ls.jar) Unloaded->Constructed->Pre-initialized
	Forge{10.13.3.1395} [Minecraft Forge] (forge-1.7.10-10.13.3.1395-1710ls.jar) Unloaded->Constructed->Pre-initialized
	furnace3d{1.4.0} [Furnace 3D] ([1.7.10] 3D Furnace-1.4 (1).jar) Unloaded->Constructed->Pre-initialized
	AgriCraft{1.7.10-1.3.1} [AgriCraft] (AgriCraft-1.7.10-1.3.1.jar) Unloaded->Constructed->Pre-initialized
	AppleCore{1.1.0} [AppleCore] (AppleCore-mc1.7.10-1.1.0 (2).jar) Unloaded->Constructed->Pre-initialized
	BnBTweaks{${version}} [Blood N' Bones Tweaks] (BnBTweaks-mc1.7.10-v1.0.1.jar) Unloaded->Constructed->Pre-initialized
	buffedtools{1.1.1710.1} [Buffed Tools] (BuffedTools-1.1.1710.7.jar) Unloaded->Constructed->Errored
	cannibalism{1.0.2} [Cannibalism] (Cannibalism-1.0.2-1.7.10.jar) Unloaded->Constructed->Pre-initialized
	BuildMod{v1.0} [Build Mod] (coroutil-1.1.2 for MC v1.7.10.jar) Unloaded->Constructed->Pre-initialized
	CoroPets{v1.0} [CoroPets] (coroutil-1.1.2 for MC v1.7.10.jar) Unloaded->Constructed->Pre-initialized
	CoroAI{v1.0} [CoroAI] (coroutil-1.1.2 for MC v1.7.10.jar) Unloaded->Constructed->Pre-initialized
	ExtendedRenderer{v1.0} [Extended Renderer] (coroutil-1.1.2 for MC v1.7.10.jar) Unloaded->Constructed->Pre-initialized
	ConfigMod{v1.0} [Extended Mod Config] (coroutil-1.1.2 for MC v1.7.10.jar) Unloaded->Constructed->Pre-initialized
	MetallurgyCore{4.0.4} [Metallurgy Core] (MetallurgyCore-1.7.10-4.0.4.18 (5).jar) Unloaded->Constructed->Pre-initialized
	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2 (6).jar) Unloaded->Constructed->Pre-initialized
	TConstruct{1.7.10-1.8.5.build957} [Tinkers' Construct] (TConstruct-1.7.10-1.8.5.jar) Unloaded->Constructed->Pre-initialized
	Metallurgy{4.0.8} [Metallurgy 4] (Metallurgy-1.7.10-4.0.8.97.jar) Unloaded->Constructed->Pre-initialized
	ExtraTiC{1.4.5} [ExtraTiC] (ExtraTiC-1.7.10-1.4.5.jar) Unloaded->Constructed->Pre-initialized
	HostileWorlds{0.5.0} [Hostile Worlds] (HostileWorlds-0.5.1.jar) Unloaded->Constructed->Pre-initialized
	IguanaTweaks{2A} [Iguana Tweaks] (IguanaTweaks-1.7.10-2A.jar) Unloaded->Constructed->Pre-initialized
	MineTweaker3{3.0.9B} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.9C (1).jar) Unloaded->Constructed->Pre-initialized
	MTRM{1.0} [MineTweakerRecipeMaker] (MineTweakerRecipeMaker-1.7.10-1.1.0.11.jar) Unloaded->Constructed->Pre-initialized
	MobProperties{0.4.0} [Mob Properties] (MobProperties-1.7.10-0.4.0.jar) Unloaded->Constructed->Pre-initialized
	ParticleMan{v1.0} [Particle Man] (ParticleMan-1.4.1.jar) Unloaded->Constructed->Pre-initialized
	RatMod{1.4} [Rat Mod] (RatMod-1.4.jar) Unloaded->Constructed->Pre-initialized
	realisticpain{1.3.1} [Realistic Pain] (Realistic Pain-1.3.1-1.7.10.jar) Unloaded->Constructed->Pre-initialized
	SpiceOfLife{1.2.3} [The Spice of Life] (SpiceOfLife-mc1.7.10-1.2.3 (3).jar) Unloaded->Constructed->Pre-initialized
	craftingmanager{0.7.4} [Crafting Manager] (zCraftingManager 0.7.5 mc1.7.10 (2).zip) Unloaded->Constructed->Pre-initialized
	ZAMod{v1.9.5} [Zombie Awareness] (ZombieAwareness-1.9.6.jar) Unloaded->Constructed->Pre-initialized
	HungerOverhaul{1.7.10-1.0.0.jenkins75} [Hunger Overhaul] (HungerOverhaul-1.7.10-1.0.0.jar) Unloaded->Constructed->Pre-initialized
	IguanaTweaksTConstruct{1.7.10-2.1.5.140} [Iguana Tinker Tweaks] (IguanaTinkerTweaks-1.7.10-2.1.5.jar) Unloaded->Constructed->Pre-initialized
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '3.3.0' Renderer: 'GeForce 8800 GTX/PCIe/SSE2'
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.

**Comment by darkhax** [comment]
Yes, that is what it looks like.

**Comment by TheSlimeMan** [comment]
yea, it's just not there

**Comment by TheSlimeMan** [comment]
it doesn't even appear like a crash report

**Comment by TheSlimeMan** [comment]
it looks like the normal launcher

**Comment by darkhax** [comment]
Okay, are you on windows?

**Comment by TheSlimeMan** [comment]
yes

**Comment by darkhax** [comment]
Okay, can use make a list of all of the mods you have installed, more specifically, the names of the files? I am also going to need your version of Forge.

**Comment by TheSlimeMan** [comment]
ok...

Coremods (1.7.10 folder)
RedGearCore- 1.7.10 - 2.2.0
PotionExtension-1.7.10-1.1.0
MrTJPCore-1.0.8.16
ForgeMultipart-1.7.10-1.2.0.345
CodeChickenLib-1.7.10-1.1.3.136
Baubles-1.7.10-1.0.1.10

**Comment by darkhax** [comment]
Okay, is that everything? your initial crash report showed a few other mods installed. Also, I need your forge version

**Comment by TheSlimeMan** [comment]
lots more mods

**Comment by TheSlimeMan** [comment]
forge version 10.13.3.1428

**Comment by darkhax** [comment]
Okay, if you want help tracking down which mod is breaking your instance, I will need a list of all of your mods.

**Comment by TheSlimeMan** [comment]
full mod list tomorrow, i'm kinda exhausted and I need to eat.

**Comment by TheSlimeMan** [comment]
sry

**Comment by TheSlimeMan** [comment]
Mod List:
Coremods (see above)
PART I:
http://picpaste.com/part_1-gDdyFoVe.PNG
PART II:
http://picpaste.com/Part_2-5m3aAwcM.PNG
PART III:
http://picpaste.com/Part_3-an2egSzX.PNG
PART IV:
http://picpaste.com/Part_4-HrgGnru7.PNG
(remember, click the pic if you want it zoomed)

**Comment by TheSlimeMan** [comment]
and the (1) or (2), etc. is because i've downloaded the same versions of mods before

**Comment by TheSlimeMan** [comment]
hello?

**Comment by Ghostrec35** [comment]
Give him time to look at the stuff.

**Comment by Ghostrec35** [comment]
Not sure if it matters but it looks like there is a jar for 1.7.2 instead fo 1.7.10. ThaumcraftMobAspects.

**Comment by Ghostrec35** [comment]
Other than that I don't directly see any that are 1.8. I need to lookup the versions of the jars without versions attached though.

**Comment by Ghostrec35** [comment]
Also, there is a new prerelease of binnie-mods if you want to update that.

**Comment by Ghostrec35** [comment]
InventoryTweaks-1.59 is a 1.8 mod.

**Comment by Ghostrec35** [comment]
Those were the only apparent version errors.

**Comment by darkhax** [comment]
Thank you @Ghostrec35. That was all I saw as well. @TheSlimeMan you need to give me some time to go through it all, this is not a live chat. I am only waking up a few minutes ago.

**Comment by TheSlimeMan** [comment]
oh i'm sorry... thank you so much

**Comment by darkhax** [comment]
@TheSlimeMan Did that fix everything?

**Comment by Ghostrec35** [comment]
If this issue isn't resolved, let us know.

**Comment by TheSlimeMan** [comment]
yes, it has been resolved. thank you so much
